Add Healthcheck
husarion/realsense-docker pull request #2
Opened 2023-11-06 16:56 UTC by rafal-gorecki

2023-11-21 09:25 UTC, delihus approved these changes

2023-11-21 12:23 UTC, delihus requested changes

2023-11-21 12:23 UTC, delihus commented on Dockerfile
> +    sed -i '/find_package(std_msgs REQUIRED)/a \
std_msgs is unnecessary

2023-11-21 12:23 UTC, delihus commented on Dockerfile
> +            ament_target_dependencies(healthcheck_node rclcpp std_msgs sensor_msgs)\n \
```suggestion
            ament_target_dependencies(healthcheck_node rclcpp sensor_msgs)\n \
```

2023-11-21 12:29 UTC, delihus requested changes

2023-11-21 12:29 UTC, delihus commented on Dockerfile
> +    ros2 pkg create healthcheck_pkg --build-type ament_cmake --dependencies rclcpp std_msgs && \
```suggestion
    ros2 pkg create healthcheck_pkg --build-type ament_cmake --dependencies rclcpp sensor_msgs && \
```

2023-11-27 08:00 UTC, delihus approved these changes

2023-11-27 09:47 UTC, rafal-gorecki commented on .github/workflows/ros-docker-image.yaml
> +        ros_distro: ["humble"]
```suggestion
        ros_distro: ["humble", "iron"]
```

2023-11-27 09:47 UTC, merged